### ISSUE TITLE
Version issue 

### ISSUE THREAD

**Issue by abhishek-butola** [Bernardi23/search_map_place#35]
Because every version of search_map_place from git depends on google_maps_flutter ^0.5.13 and app depends on google_maps_flutter 1.0.0, search_map_place from git is forbidden.

**Comment by stevesaw** [comment]
I hit this issue also, anyone know how to solve?

Because search_map_place 0.3.0 depends on google_maps_flutter ^0.5.13 and no versions of search_map_place match >0.3.0 <0.4.0, search_map_place ^0.3.0 requires google_maps_flutter ^0.5.13.
So, because APP depends on both search_map_place ^0.3.0 and google_maps_flutter ^1.0.5, version solving failed.

**Comment by abhishek-butola** [comment]
You can use this fork https://github.com/abhishek-butola/search_map_place.git.

**Comment by WaheedHussainHaans** [comment]
I used the above fork but I get this error
Because every version of search_map_place from git depends on google_maps_flutter ^1.0.2 and indyleam depends on google_maps_flutter ^2.0.1, search_map_place from git is forbidden.
